### ISSUE TITLE
Backend Progress Tracker

### ISSUE THREAD

**Issue by LilDojd** [LilDojd/gabioinf#1]
# Backend

## 1. Authentication and User Management
- [x] GitHub OAuth integration
- [x] User registration and login
- [x] #2
- [x] #3

## 2. Guestbook Functionality
- [x] #5
- [x] #6
- [x] Update guestbook entry (for admins)
- [x] Delete guestbook entry (for admins)
- [x] #8
- [x] #7

## 3. Cleanup after #9 :

- [x] #10
- [x] #11
- [x] Code Organization: Some modules, particularly in the wapi need reorganizing
- [x] #17
- [x] Repository pattern
- [x] #21
- [x] #14
- [x] #19
- [x] Queries and caching
- [x] #13

## 4. Drawing Functionality
- [x] Store and retrieve user drawings (signatures)
- [ ] Convert drawings to a storable format (e.g., base64)

## 5. Blog Functionality
- [ ] Create blog posts (for admin)
- [ ] Retrieve blog posts
- [ ] Update blog posts (for admin)
- [ ] Delete blog posts (for admin)

## 6. Projects Page
- [ ] Add projects (for admin)
- [ ] Retrieve projects
- [ ] Update projects (for admin)
- [ ] Delete projects (for admin)

## 7. API Endpoints
- [x] #25
- [x] Proper error handling and status codes

## 8. Database Operations
- [x] Efficient queries for all data retrievals
- [x] Proper indexing for frequently accessed data

## 9. Security
- [x] Input validation and sanitization
- [x] CORS configuration
- [x] #24

## 10. Performance
- [x] Caching mechanisms for frequently accessed data
- [x] Pagination for large data sets (e.g., guestbook entries, blog posts)

## 11. Deployment
- [x] Configuration for deployment on shuttle.rs
- [x] Environment variable management

## 12. Testing
- [x] Unit tests for critical functions
- [ ] Integration tests for API endpoints

## 13. Auth and Authz
- [x] #27
- [x] #28
