### ISSUE TITLE
Frontend issue tracker

### ISSUE THREAD

**Issue by LilDojd** [LilDojd/gabioinf#30]
# Frontend

## 1. Signature stuff
- [x] #32
- [x] #33
- [x] #56
- [x] Lift user to context and use_effect to update in guestbook (and potentially blog)
- [x] #59

## 2. Deployment
- [x] #37
- [x] #38

## 3. Blog
- [x] Implement blog

## 4. Visuals
- [x] Ask wife to draw some more stuff
- [x] #76
- [x] Github app logo

## 5. Dioxus
- [x] #31
- [x] #34
- [x] #41
- [x] Error boundary
- [x] Basic index.html until wasm is loaded
- [x] #54

## 6. Misc
- [x] #40
- [x] #39
- [x] Empty tailwind.css on docker build
- [x] https://github.com/danielroe/page-speed.dev
- [x] lighthouse
- [x] accesibility
- [x] #69
- [x] #73
- [x] #74
- [x] #90
- [x] Switch to use_server_future
- [x] Tweak caching

**Comment by LilDojd** [comment]
Now that assets are properly loaded, we prolly don't need to serve custom index.html template
